services:
  airline-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: airline-backend

    restart: unless-stopped

    ports:
      - "127.0.0.1:8081:8081"

    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://ep-tiny-night-b1ydnyk0.c-5.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      SPRING_DATASOURCE_USERNAME: "neondb_owner"
      SPRING_DATASOURCE_PASSWORD: "npg_oJ21CsYWzTie"

      JWT_SECRET: "${JWT_SECRET}"

    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 1200M

