CREATE TABLE airlines (
    id UUID PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    iata_code VARCHAR(10) UNIQUE,
    numeric_code VARCHAR(10) UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    settlement_currency VARCHAR(10) DEFAULT 'USD',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
