CREATE TABLE price_list_entries (
    id UUID PRIMARY KEY,
    price_list_id UUID NOT NULL REFERENCES price_lists(id) ON DELETE CASCADE,
    departure VARCHAR(100) NOT NULL,
    destination VARCHAR(100) NOT NULL,
    passenger_type VARCHAR(50) NOT NULL,
    price DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    commission DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(10) NOT NULL DEFAULT 'EGP',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
